### ISSUE TITLE
[Question]: Can this be used to serve and filter both DNS queries from the phone and from tethering clients ?

### ISSUE THREAD

**Issue by elovin** [quindecim/dnscrypt-proxy-android#5]
Hi, I was wondering whether it is possible to integrate dnscrypt-proxy into android so that both queries from the phone itself and also from tethering clients can be serviced and filtered ? (e.g. hotspot or usb-tethering clients)

**Comment by elovin** [comment]
Never mind, of course its possible, just redirect the dns queries with iptables to dnscrypt-proxy

**Comment by quindecim** [comment]
@elovin Exactly. It already work like this.
